FROM node:21-alpine3.18

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
# Add a build argument for the GitHub token
ARG GITHUB_TOKEN

# Configure npm with the GitHub token during build
RUN echo "@iacobalexandrugeorgian:registry=https://npm.pkg.github.com/IacobAlexandruGeorgian" >> .npmrc && \
    echo "//npm.pkg.github.com/:_authToken={{GITHUB_TOKEN}}" >> .npmrc && \
    npm install && npm install -g nodemon

EXPOSE 4001

CMD [ "npm", "run", "dev" ]
