namespace = "production"
serviceName = "jobber-gateway"
service = "Jobber Gateway"

def groovyMethods

m1 = System.currentTimeMillis()

pipeline {
  agent {
    label 'Jenkins-Agent'
  }

  tools {
    nodejs "NodeJS"
    dockerTool "Docker"
  }

  environment {
    DOCKER_CREDENTIALS = credentials("dockerhub")
    IMAGE_NAME = "iacobalexbr" + "/" + "jobber-gateway"
    IMAGE_TAG = "stable-${BUILD_NUMBER}"
  }

  stages {
    stage("Cleanup Workspace") {
      steps {
        cleanWs()
      }
    }

    stage("Prepare Environment") {
      steps {
        sh "[ -d pipeline ] || mkdir pipeline"
        dir("pipeline") {
          // Add your jenkins automation url to url field
          git branch: 'main', credentialsId: 'github', url: ''
          script {
            groovyMethods = load("functions.groovy")
          }
        }
        // Add your user url to url field
        git branch: 'main', credentialsId: 'github', url: 'https://github.com/IacobAlexandruGeorgian/Node-React-Ecommerce'
        dir("1-gateway-service") {
          sh 'npm install'
        }
      }
    }

    stage("Lint Check") {
      steps {
        dir("1-gateway-service") {
          sh 'npm run lint:check'
        }
      }
    }

    stage("Code Format Check") {
      steps {
        dir("1-gateway-service") {
          sh 'npm run prettier:check'
        }
      }
    }

    stage("Unit Test") {
      steps {
        dir("1-gateway-service") {
          sh 'npm run test'
        }
      }
    }

    stage("Build and Push") {
      steps {
        dir("1-gateway-service") {
          sh 'docker login -u $DOCKERHUB_CREDENTIAL_USR --password $DOCKERHUB_CREDENTIALS_PSW'
          sh "docker build -t $IMAGE_NAME ."
          sh "docker tag $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG"
          sh "docker tag $IMAGE_NAME $IMAGE_NAME:stable"
          sh "docker push $IMAGE_NAME:$IMAGE_TAG"
          sh "docker push $IMAGE_NAME:stable"
        }
      }
    }

    stage("Clean Artifacts") {
      steps {
        dir("1-gateway-service") {
          sh "docker rmi $IMAGE_NAME:$IMAGE_TAG"
          sh "docker rmi $IMAGE_NAME:stable"
        }
      }
    }

    stage("Create New Pods") {
      steps {
        withKubeCredentials(kubectlCredentials: [[caCertificate: '', clusterName: 'minikube', contextName: 'minikube', credentialsId: 'jenkins-k8s-token', namespace: '', serverUrl: 'https://127.0.0.1:61279']]) {
          script {
            def pods = groovyMethods.findPodsFromName("${namespace}", "${serviceName}")
            for (podName in pods) {
              sh """
                kubectl delete -n ${namespace} pod ${podName}
                sleep 10s
              """
            }
          }
        }
      }
    }
  }
  post {
    success {
      script {
        m2 = System.currentTimeMillis()
        def durTime = groovyMethods.durationTime(m1, m2)
        def author = groovyMethods.readCommitAuthor()
        groovyMethods.notifySlack("", "jobber-jenkins", [
        				[
        					title: "BUILD SUCCEEDED: ${service} Service with build number ${env.BUILD_NUMBER}",
        					title_link: "${env.BUILD_URL}",
        					color: "good",
        					text: "Created by: ${author}",
        					"mrkdwn_in": ["fields"],
        					fields: [
        						[
        							title: "Duration Time",
        							value: "${durTime}",
        							short: true
        						],
        						[
        							title: "Stage Name",
        							value: "Production",
        							short: true
        						],
        					]
        				]
        		]
        )
      }
    }
    failure {
      script {
        m2 = System.currentTimeMillis()
        def durTime = groovyMethods.durationTime(m1, m2)
        def author = groovyMethods.readCommitAuthor()
        groovyMethods.notifySlack("", "jobber-jenkins", [
        				[
        					title: "BUILD FAILED: ${service} Service with build number ${env.BUILD_NUMBER}",
        					title_link: "${env.BUILD_URL}",
        					color: "error",
        					text: "Created by: ${author}",
        					"mrkdwn_in": ["fields"],
        					fields: [
        						[
        							title: "Duration Time",
        							value: "${durTime}",
        							short: true
        						],
        						[
        							title: "Stage Name",
        							value: "Production",
        							short: true
        						],
        					]
        				]
        		]
        )
      }
    }
  }
}
